#!/usr/bin/env node
/**
 * Brand pipeline — turns brands/<id>/brand.json into a fully-themed build.
 *
 *   BRAND=lks-attire npm run build          (default brand)
 *   BRAND=_template PALETTE=indigo-kantha npm run build
 *
 * Outputs
 *   dist/                       static assets served by the Worker (storefront + /admin)
 *   dist/brand.css              storefront design tokens (CSS custom properties)
 *   dist/admin/brand.css        admin design tokens
 *   dist/brand.json             public brand info consumed by both front-ends
 *   dist/manifest.webmanifest   PWA manifest
 *   dist/robots.txt
 *   dist/assets/ph/*.svg        generated placeholder product art in brand colours
 *   dist-seed/seed.sql          idempotent seed data (categories, zones, settings, demo catalogue)
 *   worker/src/brand.generated.ts  typed brand constants for the Worker (SEO, order prefix)
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync, cpSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const brandId = process.env.BRAND || "lks-attire";
const brandFile = join(root, "brands", brandId, "brand.json");
if (!existsSync(brandFile)) {
  console.error(`✖ Brand "${brandId}" not found at ${brandFile}`);
  process.exit(1);
}
const brand = JSON.parse(readFileSync(brandFile, "utf8"));
validateBrand(brand);
const paletteId = process.env.PALETTE || brand.activePalette;
const palette = brand.palettes[paletteId];
if (!palette) {
  console.error(`✖ Palette "${paletteId}" not defined. Available: ${Object.keys(brand.palettes).join(", ")}`);
  process.exit(1);
}

const dist = join(root, "dist");
const seedDir = join(root, "dist-seed");
rmSync(dist, { recursive: true, force: true });
rmSync(seedDir, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
mkdirSync(seedDir, { recursive: true });
cpSync(join(root, "public"), dist, { recursive: true });
cpSync(join(root, "admin"), join(dist, "admin"), { recursive: true });
// Brand photos/logo prepared by scripts/prepare-brand-images.mjs
const brandAssets = join(root, "brands", brandId, "assets");
if (existsSync(brandAssets)) cpSync(brandAssets, join(dist, "assets", "brand"), { recursive: true });

// ---------- 1. Design tokens ----------
const kebab = (s) => s.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase());
const d = brand.design;
const storeVars = [
  ...Object.entries(palette).filter(([k]) => k !== "label").map(([k, v]) => `  --c-${kebab(k)}: ${v};`),
  `  --radius: ${d.radius};`,
  `  --radius-btn: ${d.buttonShape === "pill" ? "999px" : d.buttonShape === "square" ? "4px" : d.radius};`,
  `  --font-display: "${d.fonts.display}", Georgia, "Times New Roman", serif;`,
  `  --font-body: "${d.fonts.body}", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;`,
  `  --space: ${d.density === "compact" ? "0.85" : "1"};`,
];
writeFileSync(
  join(dist, "brand.css"),
  `/* Generated by scripts/build-brand.mjs — brand "${brand.id}", palette "${paletteId}". Do not edit. */\n:root {\n${storeVars.join("\n")}\n}\n`,
);
const a = brand.admin;
writeFileSync(
  join(dist, "admin", "brand.css"),
  `/* Generated — admin tokens for "${brand.id}" */\n:root {\n  --a-primary: ${a.primary};\n  --a-primary-deep: ${a.primaryDeep};\n  --a-pink: ${a.pink};\n  --a-bg: ${a.bg};\n}\n`,
);

// ---------- 2. Public brand JSON ----------
const publicBrand = {
  id: brand.id,
  name: brand.name,
  shortName: brand.shortName,
  tagline: brand.tagline,
  description: brand.description,
  logo: { wordmark: brand.logo.wordmark, monogram: brand.logo.monogram, image: brand.logo.image ?? null, imageLarge: brand.logo.imageLarge ?? null },
  orderPrefix: brand.orderPrefix,
  domain: brand.domain,
  locale: brand.locale,
  palette: paletteId,
  design: { heroStyle: d.heroStyle, motif: d.motif, cardStyle: d.cardStyle },
  contact: brand.contact,
  location: brand.location,
  social: brand.social,
};
writeFileSync(join(dist, "brand.json"), JSON.stringify(publicBrand, null, 2));

// ---------- 3. HTML placeholders ----------
const jsonLdStore = {
  "@context": "https://schema.org",
  "@type": "ClothingStore",
  name: brand.name.en,
  alternateName: brand.name.bn,
  description: brand.description.en,
  url: `https://${brand.domain}/`,
  telephone: brand.contact.phone,
  email: brand.contact.email,
  image: `https://${brand.domain}${brand.logo.ogImage ?? "/assets/og-default.svg"}`,
  logo: brand.logo.imageLarge ? `https://${brand.domain}${brand.logo.imageLarge}` : undefined,
  priceRange: "৳৳",
  currenciesAccepted: "BDT",
  paymentAccepted: "Cash on Delivery, bKash, Nagad, Rocket, Card",
  address: {
    "@type": "PostalAddress",
    streetAddress: brand.location.street.en,
    addressLocality: brand.location.city.en,
    addressRegion: brand.location.region.en,
    postalCode: brand.location.postalCode,
    addressCountry: brand.location.country,
  },
  geo: { "@type": "GeoCoordinates", latitude: brand.location.lat, longitude: brand.location.lng },
  sameAs: Object.values(brand.social).filter(Boolean),
};
const replacements = {
  BRAND_ID: brand.id,
  BRAND_NAME_EN: brand.name.en,
  BRAND_NAME_BN: brand.name.bn,
  BRAND_MONOGRAM: brand.logo.monogram,
  LOGO_HTML: brand.logo.image
    ? `<img src="${brand.logo.image}" alt="" width="46" height="46" decoding="async">`
    : brand.logo.monogram,
  OG_IMAGE: brand.logo.ogImage ?? "/assets/og-default.svg",
  ICON: brand.logo.icon ?? "/assets/icon.svg",
  HERO_IMAGE: brand.seed.banners?.find((b) => b.placement === "hero")?.image ?? "",
  TAGLINE_EN: brand.tagline.en,
  TAGLINE_BN: brand.tagline.bn,
  DESCRIPTION_EN: brand.description.en,
  DOMAIN: brand.domain,
  THEME_COLOR: palette.primary,
  ADMIN_THEME_COLOR: a.primary,
  FONTS_QUERY: d.fonts.googleFontsQuery,
  DEFAULT_LANG: brand.locale.default,
  HERO: d.heroStyle,
  MOTIF: d.motif,
  CARD: d.cardStyle,
  JSONLD_STORE: JSON.stringify(jsonLdStore).replace(/</g, "\\u003c"),
  BUILD_ID: Date.now().toString(36),
};
const htmlEscape = (s) => String(s).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
for (const file of walk(dist)) {
  if (!/\.(html|webmanifest|js|txt|xml)$/.test(file)) continue;
  let src = readFileSync(file, "utf8");
  if (!src.includes("{{")) continue;
  src = src.replace(/\{\{([A-Z_]+)\}\}/g, (m, key) => {
    if (!(key in replacements)) return m;
    const v = replacements[key];
    return key === "JSONLD_STORE" || key === "LOGO_HTML" || !file.endsWith(".html") ? v : htmlEscape(v);
  });
  writeFileSync(file, src);
}

// ---------- 4. Manifest, robots, OG image ----------
writeFileSync(
  join(dist, "manifest.webmanifest"),
  JSON.stringify(
    {
      name: brand.name.en,
      short_name: brand.shortName,
      description: brand.tagline.en,
      start_url: "/",
      display: "standalone",
      background_color: palette.bg,
      theme_color: palette.primary,
      lang: brand.locale.default,
      icons: brand.logo.icon
        ? [
            { src: brand.logo.icon, sizes: "512x512", type: "image/png", purpose: "any" },
            { src: brand.logo.icon.replace("-512", "-192"), sizes: "192x192", type: "image/png", purpose: "any" },
          ]
        : [{ src: "/assets/icon.svg", sizes: "any", type: "image/svg+xml", purpose: "any maskable" }],
    },
    null,
    2,
  ),
);
writeFileSync(
  join(dist, "robots.txt"),
  `User-agent: *\nAllow: /\nDisallow: /admin/\nDisallow: /api/\nDisallow: /checkout\nDisallow: /account\n\nSitemap: https://${brand.domain}/sitemap.xml\n`,
);
mkdirSync(join(dist, "assets", "ph"), { recursive: true });
writeFileSync(join(dist, "assets", "icon.svg"), iconSvg());
writeFileSync(join(dist, "admin", "icon.svg"), iconSvg(a.primary, "#fff"));
writeFileSync(join(dist, "assets", "og-default.svg"), ogSvg());

// ---------- 5. Seed SQL + placeholder art ----------
const sql = [];
const q = (v) => (v === null || v === undefined ? "NULL" : typeof v === "number" ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const now = new Date().toISOString();

sql.push("-- Generated seed for brand " + brand.id + " (" + now + "). Safe to re-run: uses INSERT OR IGNORE.");
const settings = {
  store: {
    name_en: brand.name.en, name_bn: brand.name.bn,
    tagline_en: brand.tagline.en, tagline_bn: brand.tagline.bn,
    phone: brand.contact.phone, whatsapp: brand.contact.whatsapp, email: brand.contact.email,
    address_en: `${brand.location.street.en}, ${brand.location.city.en}`,
    address_bn: `${brand.location.street.bn}, ${brand.location.city.bn}`,
    hours_en: brand.contact.hours.en, hours_bn: brand.contact.hours.bn,
    announcement_en: "Cash on Delivery all over Bangladesh · Easy 3-day exchange",
    announcement_bn: "সারা বাংলাদেশে ক্যাশ অন ডেলিভারি · ৩ দিনের সহজ এক্সচেঞ্জ",
    // Editable from Admin → Settings → Branding (logo upload, social links).
    logo_url: brand.logo.image ?? "",
    facebook_url: brand.social.facebook ?? "",
    instagram_url: brand.social.instagram ?? "",
    tiktok_url: brand.social.tiktok ?? "",
  },
  payments: {
    cod: { enabled: true },
    bkash: { enabled: true, mode: "manual", manualNumber: brand.contact.whatsapp.replace(/^88/, ""), accountType: "Personal" },
    nagad: { enabled: true, mode: "manual", manualNumber: brand.contact.whatsapp.replace(/^88/, ""), accountType: "Personal" },
    rocket: { enabled: false, mode: "manual", manualNumber: "", accountType: "Personal" },
    card: { enabled: false, provider: "sslcommerz" },
  },
  notifications: { sms: true, whatsapp: false, email: true, ownerPhone: brand.contact.phone },
  sms_templates: {
    placed: { en: "Hi {name}, your order {order_no} (৳{total}) is received. We will call to confirm. - {store}", bn: "প্রিয় {name}, আপনার অর্ডার {order_no} (৳{total}) পেয়েছি। কনফার্ম করতে আমরা কল করব। - {store}" },
    confirmed: { en: "Order {order_no} is confirmed. Thank you! - {store}", bn: "অর্ডার {order_no} কনফার্ম হয়েছে। ধন্যবাদ! - {store}" },
    packed: { en: "Order {order_no} is packed and ready to ship. - {store}", bn: "অর্ডার {order_no} প্যাক করা হয়েছে। - {store}" },
    shipped: { en: "Order {order_no} shipped via {courier}. Tracking: {tracking}. - {store}", bn: "অর্ডার {order_no} {courier} দিয়ে পাঠানো হয়েছে। ট্র্যাকিং: {tracking}। - {store}" },
    delivered: { en: "Order {order_no} delivered. Hope you love it! - {store}", bn: "অর্ডার {order_no} ডেলিভারি হয়েছে। আশা করি পছন্দ হবে! - {store}" },
    cancelled: { en: "Order {order_no} was cancelled. Call us if this is a mistake. - {store}", bn: "অর্ডার {order_no} বাতিল হয়েছে। ভুল হলে আমাদের কল করুন। - {store}" },
    returned: { en: "Return for order {order_no} is recorded. - {store}", bn: "অর্ডার {order_no} রিটার্ন গ্রহণ করা হয়েছে। - {store}" },
    otp: { en: "Your {store} code is {code}. It expires in 10 minutes.", bn: "{store} কোড: {code}। ১০ মিনিটের মধ্যে ব্যবহার করুন।" },
  },
  seo: {
    title_en: `${brand.name.en} — ${brand.tagline.en}`,
    title_bn: `${brand.name.bn} — ${brand.tagline.bn}`,
    description_en: brand.description.en,
    description_bn: brand.description.bn,
  },
  inventory: { lowStockDefault: 3 },
  integrations: { ga4: "", metaPixel: "", cfBeacon: "", instagramHandle: (brand.social.instagram || "").split("/").pop() || "" },
};
for (const [k, v] of Object.entries(settings)) sql.push(`INSERT OR IGNORE INTO settings (key, value) VALUES (${q(k)}, ${q(JSON.stringify(v))});`);

let sort = 0;
const catSlugs = [];
for (const c of brand.seed.categories) {
  sql.push(`INSERT OR IGNORE INTO categories (slug, name_en, name_bn, sort_order) VALUES (${q(c.slug)}, ${q(c.en)}, ${q(c.bn)}, ${sort++});`);
  catSlugs.push(c.slug);
  let childSort = 0;
  for (const ch of c.children || []) {
    sql.push(
      `INSERT OR IGNORE INTO categories (slug, parent_id, name_en, name_bn, sort_order) VALUES (${q(ch.slug)}, (SELECT id FROM categories WHERE slug=${q(c.slug)}), ${q(ch.en)}, ${q(ch.bn)}, ${childSort++});`,
    );
    catSlugs.push(ch.slug);
  }
}
brand.seed.deliveryZones.forEach((z, i) => {
  sql.push(
    `INSERT OR IGNORE INTO delivery_zones (code, name_en, name_bn, fee, free_shipping_min, district_ids, upazila_ids, eta_en, eta_bn, is_default, sort_order) VALUES (${q(z.code)}, ${q(z.en)}, ${q(z.bn)}, ${z.fee}, ${z.freeOver ?? "NULL"}, ${q(JSON.stringify(z.districtIds))}, ${q(JSON.stringify(z.upazilaIds))}, ${q(z.etaEn)}, ${q(z.etaBn)}, ${z.isDefault ? 1 : 0}, ${i});`,
  );
});

const hues = [palette.primary, palette.accent, palette.gold, palette.motifA, palette.motifB];
// Real products (brand.seed.products, with photos in brands/<id>/assets) come first; optional demo
// products (generated SVG art) fill the other categories until the shop uploads its own.
const catalogue = [
  ...(brand.seed.products ?? []).map((p) => ({ ...p, real: true })),
  ...(brand.seed.demoProducts ? demoCatalogue() : []),
];
catalogue.forEach((p, i) => {
  let imgs = p.images;
  if (!imgs) {
    imgs = [1, 2].map((n) => `/assets/ph/${p.slug}-${n}.svg`);
    imgs.forEach((src, n) => writeFileSync(join(dist, src), productSvg(p.art, p.hue, n, i)));
  }
  sql.push(
    `INSERT OR IGNORE INTO products (slug, sku, name_en, name_bn, description_en, description_bn, fabric_en, fabric_bn, care_en, care_bn, category_id, price, sale_price, tags, images, status, is_featured, sold_count, created_at) VALUES (${[
      p.slug, p.sku, p.en, p.bn, p.descEn, p.descBn, p.fabricEn, p.fabricBn,
      p.careEn ?? "Gentle hand wash in cold water. Dry in shade. Iron on medium heat.",
      p.careBn ?? "ঠান্ডা পানিতে হালকা হাতে ধুয়ে নিন। ছায়ায় শুকান। মাঝারি তাপে আয়রন করুন।",
    ].map(q).join(", ")}, (SELECT id FROM categories WHERE slug=${q(p.cat)}), ${p.price}, ${p.sale ?? "NULL"}, ${q(p.tags ?? "")}, ${q(JSON.stringify(imgs))}, 'active', ${p.featured ? 1 : 0}, ${p.sold ?? 0}, ${q(new Date(Date.now() - i * 86400000 * 2).toISOString())});`,
  );
  for (const size of p.sizes) {
    for (const [color, hex] of p.colors) {
      const stock = (i * 7 + size.length * 3 + color.length) % 9 === 0 ? 2 : 4 + ((i + size.length + color.length) % 12);
      sql.push(
        `INSERT OR IGNORE INTO product_variants (product_id, sku, size, color, color_hex, stock) VALUES ((SELECT id FROM products WHERE slug=${q(p.slug)}), ${q(`${p.sku}-${size}-${color}`.replace(/\s+/g, "").toUpperCase())}, ${q(size)}, ${q(color)}, ${q(hex)}, ${stock});`,
      );
    }
  }
});
if (catalogue.length) {
  const reviews = [
    ["ruby-organza-three-piece", "Farzana A.", 5, "The organza and beadwork look even better in person. Delivered to Dhaka in 2 days."],
    ["blush-organza-three-piece", "Nusrat J.", 5, "Wore it to my cousin's holud — everyone asked where I got it!"],
    ["maroon-embroidered-kurti", "Sadia R.", 4, "Beautiful stonework, fits well. Size guide was helpful."],
    ["tangail-taant-saree-red-gold", "Tahmina K.", 5, "Beautiful weave and the colour is exactly like the photo."],
    ["lawn-three-piece-floral", "Rumana S.", 5, "Stitching is neat and the fabric is soft for summer."],
  ];
  for (const [slug, name, rating, body] of reviews) {
    sql.push(
      `INSERT INTO reviews (product_id, name, rating, body, status) SELECT id, ${q(name)}, ${rating}, ${q(body)}, 'approved' FROM products WHERE slug=${q(slug)} AND NOT EXISTS (SELECT 1 FROM reviews r WHERE r.product_id = products.id AND r.name = ${q(name)});`,
    );
  }
  sql.push(
    `UPDATE products SET rating_avg = COALESCE((SELECT AVG(rating) FROM reviews WHERE reviews.product_id = products.id AND status='approved'),0), rating_count = (SELECT COUNT(*) FROM reviews WHERE reviews.product_id = products.id AND status='approved');`,
  );
}
const seedBanners =
  brand.seed.banners ??
  (brand.seed.demoProducts
    ? [
        { placement: "hero", en: "Handwoven in Tangail", bn: "টাঙ্গাইলের হাতে বোনা", subEn: "New taant sarees, straight from the loom", subBn: "তাঁত থেকে সরাসরি নতুন শাড়ি", ctaEn: "Shop sarees", ctaBn: "শাড়ি দেখুন", link: "/shop/saree" },
        { placement: "hero", en: "Everyday three-pieces", bn: "প্রতিদিনের থ্রি-পিস", subEn: "Breathable lawn and cotton for the season", subBn: "গরমে আরামদায়ক লন ও সুতি", ctaEn: "Shop now", ctaBn: "এখনই কিনুন", link: "/shop/three-piece" },
        { placement: "festive", en: "The Eid Edit", bn: "ঈদ কালেকশন", subEn: "Festive sets — COD all over Bangladesh", subBn: "উৎসবের সেট — সারা দেশে ক্যাশ অন ডেলিভারি", ctaEn: "Explore the edit", ctaBn: "কালেকশন দেখুন", link: "/shop/festive" },
      ]
    : []);
seedBanners.forEach((b, i) => {
  let img = b.image;
  if (img === undefined) {
    img = `/assets/ph/banner-${b.placement}-${i}.svg`;
    writeFileSync(join(dist, img), bannerSvg(i));
  }
  sql.push(
    `INSERT INTO banners (placement, title_en, title_bn, subtitle_en, subtitle_bn, cta_en, cta_bn, link_url, image_url, sort_order) SELECT ${[b.placement, b.en, b.bn, b.subEn ?? "", b.subBn ?? "", b.ctaEn ?? "", b.ctaBn ?? "", b.link ?? "", img || null].map(q).join(", ")}, ${i} WHERE NOT EXISTS (SELECT 1 FROM banners WHERE title_en=${q(b.en)});`,
  );
});
for (const c of brand.seed.coupons ?? []) {
  sql.push(
    `INSERT OR IGNORE INTO coupons (code, description, type, value, min_order, max_discount) VALUES (${[c.code, c.description ?? null].map(q).join(", ")}, ${q(c.type)}, ${c.value}, ${c.min_order ?? 0}, ${c.max_discount ?? "NULL"});`,
  );
}
writeFileSync(join(seedDir, "seed.sql"), sql.join("\n") + "\n");

// ---------- 6. Worker constants ----------
writeFileSync(
  join(root, "worker", "src", "brand.generated.ts"),
  `// Generated by scripts/build-brand.mjs — do not edit. Brand: ${brand.id}\nexport const BRAND = ${JSON.stringify({ ...publicBrand, themeColor: palette.primary, jsonLdStore }, null, 2)} as const;\n`,
);

console.log(`✔ Built brand "${brand.name.en}" (${brand.id}) with palette "${paletteId}" → dist/, dist-seed/seed.sql`);

// ======================================================================
function walk(dir) {
  const out = [];
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out;
}

function validateBrand(b) {
  const required = ["id", "name", "tagline", "description", "orderPrefix", "domain", "locale", "palettes", "activePalette", "design", "admin", "contact", "location", "social", "seed"];
  const missing = required.filter((k) => !(k in b));
  if (missing.length) {
    console.error(`✖ brand.json missing keys: ${missing.join(", ")}`);
    process.exit(1);
  }
  if (!/^[A-Z]{2,5}$/.test(b.orderPrefix)) {
    console.error("✖ orderPrefix must be 2–5 capital letters");
    process.exit(1);
  }
  const tokens = ["bg", "surface", "surfaceAlt", "ink", "inkSoft", "primary", "primaryInk", "accent", "accentSoft", "gold", "line", "success", "danger", "motifA", "motifB", "motifC"];
  for (const [id, p] of Object.entries(b.palettes)) {
    const miss = tokens.filter((t) => !p[t]);
    if (miss.length) {
      console.error(`✖ palette "${id}" missing tokens: ${miss.join(", ")}`);
      process.exit(1);
    }
  }
}

function iconSvg(bg = palette.primary, fg = palette.primaryInk) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><rect width="512" height="512" rx="112" fill="${bg}"/><path d="M136 420V210a120 120 0 0 1 240 0v210" fill="none" stroke="${fg}" stroke-opacity=".35" stroke-width="14"/><text x="256" y="330" text-anchor="middle" font-family="Georgia,serif" font-size="170" font-weight="600" fill="${fg}">${brand.logo.monogram}</text><g fill="${palette.gold}"><rect x="136" y="400" width="240" height="10"/><rect x="136" y="418" width="240" height="4"/></g></svg>`;
}

function ogSvg() {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630"><rect width="1200" height="630" fill="${palette.bg}"/><path d="M760 630V300a180 180 0 0 1 360 0v330z" fill="${palette.accentSoft}"/><text x="80" y="300" font-family="Georgia,serif" font-size="96" font-weight="600" fill="${palette.ink}">${brand.name.en.replace(/&/g, "&amp;")}</text><text x="80" y="380" font-family="sans-serif" font-size="40" fill="${palette.inkSoft}">${brand.tagline.en}</text>${stripe(0, 560, 1200, 70)}</svg>`;
}

function stripe(x, y, w, h) {
  // The "paar" — a woven border band used as the brand motif.
  const bands = [
    [0, 0.18, palette.motifA], [0.18, 0.08, palette.motifB], [0.26, 0.06, palette.motifC],
    [0.32, 0.36, palette.motifA], [0.68, 0.06, palette.motifC], [0.74, 0.08, palette.motifB], [0.82, 0.18, palette.motifA],
  ];
  return bands.map(([o, s, c]) => `<rect x="${x}" y="${y + o * h}" width="${w}" height="${s * h}" fill="${c}"/>`).join("");
}

function productSvg(art, hueIdx, variant, seed) {
  const c1 = hues[hueIdx % hues.length];
  const c2 = hues[(hueIdx + 2) % hues.length];
  const bg = variant === 0 ? palette.surfaceAlt : palette.accentSoft;
  const shapes = {
    drape: `<path d="M170 170 C 260 240, 230 420, 300 720 L 470 720 C 420 520, 470 330, 430 170 Z" fill="url(#g)"/><path d="M430 170 C 470 330, 420 520, 470 720" fill="none" stroke="${palette.gold}" stroke-width="18" stroke-opacity=".9"/><path d="M230 260 C 280 360, 270 480, 330 700" fill="none" stroke="#fff" stroke-opacity=".25" stroke-width="6"/><path d="M300 230 C 350 330, 340 470, 390 700" fill="none" stroke="#fff" stroke-opacity=".18" stroke-width="5"/>`,
    kameez: `<path d="M250 170 L 350 170 L 400 200 L 450 330 L 410 345 L 385 280 L 400 700 L 200 700 L 215 280 L 190 345 L 150 330 L 200 200 Z" fill="url(#g)"/><path d="M270 170 Q 300 215 330 170" fill="none" stroke="${palette.gold}" stroke-width="8"/><path d="M200 660 L 400 660" stroke="${palette.gold}" stroke-width="14"/>`,
    abaya: `<path d="M260 160 Q 300 140 340 160 L 380 210 L 430 700 L 170 700 L 220 210 Z" fill="url(#g)"/><path d="M300 180 L 300 700" stroke="#fff" stroke-opacity=".2" stroke-width="4"/>`,
    jhumka: `<circle cx="300" cy="250" r="26" fill="none" stroke="${c1}" stroke-width="10"/><path d="M200 420 Q 300 250 400 420 Z" fill="url(#g)"/>${Array.from({ length: 7 }, (_, k) => `<circle cx="${215 + k * 28}" cy="445" r="10" fill="${palette.gold}"/>`).join("")}`,
    shoe: `<path d="M140 520 Q 150 430 260 430 L 330 430 Q 420 440 470 500 Q 480 540 440 550 L 170 560 Q 140 555 140 520 Z" fill="url(#g)"/><path d="M230 440 Q 300 480 360 440" fill="none" stroke="${palette.gold}" stroke-width="10"/>`,
  };
  const pat = `<pattern id="p" width="36" height="36" patternUnits="userSpaceOnUse"><path d="M18 4 L32 18 L18 32 L4 18 Z" fill="none" stroke="${palette.ink}" stroke-opacity=".05" stroke-width="2"/></pattern>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 800"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${c1}"/><stop offset="1" stop-color="${c2}"/></linearGradient>${pat}</defs><rect width="600" height="800" fill="${bg}"/><rect width="600" height="800" fill="url(#p)"/><path d="M90 800V300a210 210 0 0 1 420 0v500z" fill="${palette.surface}" fill-opacity=".55"/>${shapes[art] || shapes.drape}${stripe(0, 740, 600, 60)}<text x="560" y="60" text-anchor="end" font-family="Georgia,serif" font-size="28" fill="${palette.ink}" fill-opacity=".25">${brand.logo.monogram} · ${String(seed + 1).padStart(2, "0")}</text></svg>`;
}

function bannerSvg(i) {
  const c1 = hues[i % hues.length];
  const c2 = hues[(i + 1) % hues.length];
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 900"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${c1}"/><stop offset="1" stop-color="${c2}"/></linearGradient></defs><rect width="1200" height="900" fill="${palette.accentSoft}"/><path d="M300 900V420a300 300 0 0 1 600 0v480z" fill="url(#g)"/><path d="M420 900 C 520 700, 470 520, 600 330 C 700 520, 680 700, 780 900 Z" fill="${palette.surface}" fill-opacity=".25"/><circle cx="600" cy="330" r="40" fill="${palette.gold}"/>${stripe(0, 840, 1200, 60)}</svg>`;
}

function demoCatalogue() {
  const free = ["Free Size"];
  const std = ["S", "M", "L", "XL"];
  return [
    { slug: "tangail-taant-saree-red-gold", sku: "TS-001", en: "Tangail Taant Saree — Red & Gold Paar", bn: "টাঙ্গাইল তাঁতের শাড়ি — লাল-সোনালি পাড়", cat: "tangail-saree", price: 2450, sale: 2150, sizes: free, colors: [["Red", "#A4161A"], ["Off-white", "#F4EFE6"]], art: "drape", hue: 0, featured: 1, sold: 64, tags: "tangail,taant,cotton,festive", fabricEn: "Handloom cotton, 12 hands (5.5m) with blouse piece", fabricBn: "হ্যান্ডলুম সুতি, ১২ হাত (৫.৫ মি.) ব্লাউজ পিসসহ", descEn: "Our signature Tangail taant saree with a hand-woven gold paar. Light, breathable and easy to drape — made by weavers from the Pathrail belt of Tangail.", descBn: "হাতে বোনা সোনালি পাড়ের আমাদের সিগনেচার টাঙ্গাইল তাঁতের শাড়ি। হালকা, আরামদায়ক এবং পরতে সহজ — টাঙ্গাইলের পাথরাইলের তাঁতিদের হাতে তৈরি।" },
    { slug: "soft-cotton-saree-mint-block", sku: "CS-002", en: "Soft Cotton Saree — Mint Block Print", bn: "নরম সুতি শাড়ি — মিন্ট ব্লক প্রিন্ট", cat: "cotton-saree", price: 1350, sizes: free, colors: [["Mint", "#9CCFB8"], ["Peach", "#F4B998"]], art: "drape", hue: 2, sold: 41, tags: "cotton,everyday,office", fabricEn: "Soft mulmul cotton", fabricBn: "নরম মসলিন সুতি", descEn: "An everyday cotton saree with hand-block print. Perfect for office and summer days.", descBn: "হ্যান্ড-ব্লক প্রিন্টের প্রতিদিনের সুতি শাড়ি। অফিস ও গরমের দিনের জন্য উপযুক্ত।" },
    { slug: "dhakai-jamdani-ivory", sku: "JM-003", en: "Dhakai Jamdani — Ivory Motif", bn: "ঢাকাই জামদানি — আইভরি নকশা", cat: "jamdani-saree", price: 8500, sale: 7900, sizes: free, colors: [["Ivory", "#F2E8D5"]], art: "drape", hue: 3, featured: 1, sold: 18, tags: "jamdani,heritage,gift,festive", fabricEn: "Half-silk jamdani, 84-count", fabricBn: "হাফ-সিল্ক জামদানি, ৮৪ কাউন্ট", descEn: "A heirloom-quality Dhakai jamdani with hand-woven motifs across the body and anchal.", descBn: "পুরো জমিন ও আঁচলে হাতে বোনা নকশার ঐতিহ্যবাহী ঢাকাই জামদানি।" },
    { slug: "half-silk-festive-saree-maroon", sku: "SS-004", en: "Half-Silk Festive Saree — Maroon", bn: "হাফ সিল্ক উৎসবের শাড়ি — মেরুন", cat: "silk-saree", price: 3200, sizes: free, colors: [["Maroon", "#6B1E2E"], ["Bottle Green", "#1F4D3A"]], art: "drape", hue: 1, sold: 27, tags: "silk,festive,puja,eid", fabricEn: "Half silk with zari border", fabricBn: "জরি পাড়ের হাফ সিল্ক", descEn: "Rich maroon half-silk with a zari border — made for Eid, Puja and wedding invitations.", descBn: "জরি পাড়ের গাঢ় মেরুন হাফ সিল্ক — ঈদ, পূজা ও বিয়ের দাওয়াতের জন্য।" },
    { slug: "lawn-three-piece-floral", sku: "TP-005", en: "Lawn Three-Piece — Floral Embroidery", bn: "লন থ্রি-পিস — ফ্লোরাল এমব্রয়ডারি", cat: "stitched-three-piece", price: 2200, sale: 1890, sizes: std, colors: [["Powder Blue", "#A9C6E0"], ["Blush", "#F3C6C4"]], art: "kameez", hue: 1, featured: 1, sold: 72, tags: "lawn,summer,embroidery", fabricEn: "Pakistani-style lawn, chiffon dupatta", fabricBn: "লন কাপড়, শিফন ওড়না", descEn: "A ready-to-wear lawn three-piece with delicate neck embroidery and a soft chiffon dupatta.", descBn: "গলায় সূক্ষ্ম এমব্রয়ডারি ও নরম শিফন ওড়নাসহ রেডি-টু-ওয়্যার লন থ্রি-পিস।" },
    { slug: "unstitched-georgette-three-piece-peach", sku: "TP-006", en: "Unstitched Georgette Three-Piece — Peach", bn: "আনস্টিচড জর্জেট থ্রি-পিস — পিচ", cat: "unstitched-three-piece", price: 1750, sizes: free, colors: [["Peach", "#F4B998"], ["Lilac", "#C8B3E0"]], art: "kameez", hue: 2, sold: 23, tags: "georgette,unstitched,party", fabricEn: "Georgette kameez, crepe salwar, net dupatta (2.5m + 2.5m + 2.5m)", fabricBn: "জর্জেট কামিজ, ক্রেপ সালোয়ার, নেট ওড়না (২.৫ + ২.৫ + ২.৫ মি.)", descEn: "Unstitched set so your tailor can make it just right.", descBn: "আনস্টিচড সেট — আপনার দর্জি দিয়ে মাপমতো বানিয়ে নিন।" },
    { slug: "cotton-kurti-indigo-handblock", sku: "KU-007", en: "Cotton Kurti — Indigo Handblock", bn: "সুতি কুর্তি — ইন্ডিগো হ্যান্ডব্লক", cat: "kurti", price: 950, sizes: std, colors: [["Indigo", "#2C3E73"]], art: "kameez", hue: 3, sold: 88, tags: "kurti,cotton,everyday,university", fabricEn: "100% cotton, hand-block print", fabricBn: "১০০% সুতি, হ্যান্ড-ব্লক প্রিন্ট", descEn: "An easy, breathable kurti for university and everyday wear.", descBn: "বিশ্ববিদ্যালয় ও প্রতিদিনের জন্য আরামদায়ক সুতি কুর্তি।" },
    { slug: "linen-a-line-tunic-sand", sku: "KU-008", en: "Linen A-line Tunic — Sand", bn: "লিনেন এ-লাইন টিউনিক — স্যান্ড", cat: "kurti", price: 1150, sizes: std, colors: [["Sand", "#D8C3A5"], ["Olive", "#6B7A4B"]], art: "kameez", hue: 4, sold: 19, tags: "linen,tunic,minimal", fabricEn: "Linen blend", fabricBn: "লিনেন ব্লেন্ড", descEn: "A minimal A-line tunic that pairs with jeans or palazzos.", descBn: "জিন্স বা পালাজোর সাথে মানানসই মিনিমাল এ-লাইন টিউনিক।" },
    { slug: "rayon-wrap-top-olive", sku: "WW-009", en: "Rayon Wrap Top — Olive", bn: "রেয়ন র‍্যাপ টপ — অলিভ", cat: "western", price: 890, sizes: std, colors: [["Olive", "#6B7A4B"], ["Black", "#1B1B1B"]], art: "kameez", hue: 0, sold: 15, tags: "western,top,rayon", fabricEn: "Rayon", fabricBn: "রেয়ন", descEn: "A flattering wrap top in soft rayon.", descBn: "নরম রেয়নের মানানসই র‍্যাপ টপ।" },
    { slug: "everyday-nida-abaya-black", sku: "AB-010", en: "Everyday Nida Abaya — Black", bn: "প্রতিদিনের নিদা আবায়া — কালো", cat: "abaya-hijab", price: 2600, sizes: ["52", "54", "56"], colors: [["Black", "#151515"], ["Navy", "#1E2A44"]], art: "abaya", hue: 3, sold: 34, tags: "abaya,modest,nida", fabricEn: "Premium Nida, non-see-through", fabricBn: "প্রিমিয়াম নিদা, অস্বচ্ছ", descEn: "A lightweight, flowy abaya with hidden pockets.", descBn: "লুকানো পকেটসহ হালকা ও ঢিলেঢালা আবায়া।" },
    { slug: "jersey-hijab-dusty-rose", sku: "HJ-011", en: "Jersey Hijab — Dusty Rose", bn: "জার্সি হিজাব — ডাস্টি রোজ", cat: "abaya-hijab", price: 390, sizes: free, colors: [["Dusty Rose", "#C99A9A"], ["Beige", "#D9C7AE"], ["Black", "#151515"]], art: "abaya", hue: 1, sold: 120, tags: "hijab,jersey,everyday", fabricEn: "Stretch jersey", fabricBn: "স্ট্রেচ জার্সি", descEn: "Soft, no-slip jersey hijab for all-day comfort.", descBn: "সারাদিনের আরামের জন্য নরম, পিছলে না যাওয়া জার্সি হিজাব।" },
    { slug: "bridal-katan-benarasi-red", sku: "FW-012", en: "Bridal Katan Benarasi — Red", bn: "ব্রাইডাল কাতান বেনারসি — লাল", cat: "festive", price: 14500, sale: 12900, sizes: free, colors: [["Red", "#A4161A"]], art: "drape", hue: 0, featured: 1, sold: 6, tags: "bridal,wedding,katan,benarasi", fabricEn: "Katan silk with heavy zari", fabricBn: "ভারী জরির কাতান সিল্ক", descEn: "A bridal katan with dense zari work — for the most important day.", descBn: "ঘন জরির কাজের ব্রাইডাল কাতান — জীবনের বিশেষ দিনের জন্য।" },
    { slug: "oxidised-jhumka-earrings", sku: "AC-013", en: "Oxidised Jhumka Earrings", bn: "অক্সিডাইজড ঝুমকা", cat: "accessories", price: 450, sizes: free, colors: [["Silver", "#9EA3A8"]], art: "jhumka", hue: 2, sold: 57, tags: "jewellery,jhumka,gift", fabricEn: "Oxidised German silver", fabricBn: "অক্সিডাইজড জার্মান সিলভার", descEn: "Lightweight jhumkas that go with sarees and kurtis alike.", descBn: "শাড়ি ও কুর্তি দুটোর সাথেই মানানসই হালকা ঝুমকা।" },
    { slug: "embroidered-kolhapuri-flats", sku: "FT-014", en: "Embroidered Kolhapuri Flats", bn: "এমব্রয়ডারি কোলাপুরি ফ্ল্যাট", cat: "footwear", price: 1250, sizes: ["36", "37", "38", "39", "40"], colors: [["Tan", "#B07A4F"]], art: "shoe", hue: 4, sold: 22, tags: "footwear,flats,ethnic", fabricEn: "Synthetic leather upper, cushioned sole", fabricBn: "সিনথেটিক লেদার, নরম সোল", descEn: "Comfortable embroidered flats for festive days.", descBn: "উৎসবের দিনের জন্য আরামদায়ক এমব্রয়ডারি ফ্ল্যাট।" },
  ];
}
